### PR TITLE
Improve developers experience

### PR DESCRIPTION
**Pull request by TurboThon**
## Purpose

Improve developers experience.

## Proposal

- [x] add a basic circleci
- [x] add pull request and issue templates

### CODE REVIEW

**Comment by sampaccoud** [comment]
@thomas-borot That's a good start for a CI. 
We usually add an extra conf to our gitlint to check gitmojis :hand_over_mouth: See [here](https://github.com/openfun/clearboard/tree/main/gitlint) and [here](https://github.com/openfun/clearboard/blob/main/.gitlint#L23)

**Comment by sampaccoud** [comment]
@thomas-borot maybe run the packer build as well?

**Comment by TurboThon** [comment]
> @thomas-borot That's a good start for a CI.
> We usually add an extra conf to our gitlint to check gitmojis 🤭 See [here](https://github.com/openfun/clearboard/tree/main/gitlint) and [here](https://github.com/openfun/clearboard/blob/main/.gitlint#L23)

I added the corresponding configuration, thanks for the links !

> @thomas-borot maybe run the packer build as well?

Packer builds its image using a Scaleway instance, and creates an image inside the cloud. Do you really want this feature ?

**Comment by sampaccoud** [comment]
> Packer builds its image using a Scaleway instance, and creates an image inside the cloud. Do you really want this feature ?

@thomas-borot ok maybe not in this PR then. It should be run locally in the CI with another local builder... maybe don't do it in the frame of the current project :sweat_smile:

**Review by sampaccoud — APPROVED** [review]

**Pull request merged**
